# Data Analytics Capstone Notebook

### Import Libraries

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import seaborn as sns

### Import Data Source

In [5]:
df = pd.read_csv('bodyfat.csv')

### Data Description
- The data set has 15 features. 
- The data set had 252 instances.
- The data types included are float and int.
- There are no missing values.

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Density                  252 non-null    float64
 1   BodyFat                  252 non-null    float64
 2   Age                      252 non-null    int64
 3   Weight                   252 non-null    float64
 4   Height                   252 non-null    float64
 5   Neck                     252 non-null    float64
 6   Chest                    252 non-null    float64
 7   Abdomen                  252 non-null    float64
 8   Hip                      252 non-null    float64
 9   Thigh                    252 non-null    float64
 10  Knee                     252 non-null    float64
 11  Ankle                    252 non-null    float64
 12  Biceps                   252 non-null    float64
 13  Forearm                  252 non-null    float64
 14  Wrist                    252 non-null    float64
 15  Height_Meters            252 non-null    float64
 16  Weight_kg                252 non-null    float64
 17  BMI                      252 non-null    float64
 18  BMI Body Fat             252 non-null    float64
 19  Height (m)               252 non-null    float64
 20  Weight (kg)              252 non-null    float64
 21  Height (cm)              252 non-null    float64
 22  neck_in                  252 non-null    float64
 23  abdomen_in               252 non-null    float64
 24  Navy_Body_Fat            252 non-null    float64
 25  BMI_Body_Fat_Percentage  252 non-null    float64
 26  BMI_Body_Fat             252 non-null    float64
dtypes: float64(26), int64(1)
memory usage: 53.3 KB

In [25]:
df.head()

,Density,BodyFat,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,...,BMI,BMI Body Fat,Height (m),Weight (kg),Height (cm),neck_in,abdomen_in,Navy_Body_Fat,BMI_Body_Fat_Percentage,BMI_Body_Fat
0,1.0708,12.3,23,154.25,67.75,36.2,93.1,85.2,94.5,59.0,...,23.63,19.052135,1.72085,69.966566,91.948,14.251976,33.543325,19.08,17.44,17.44
1,1.0853,6.1,22,173.25,72.25,38.5,93.6,83.0,98.7,58.7,...,23.33,18.701206,1.83515,78.584814,97.790,15.157489,32.677183,13.52,16.86,16.86
2,1.0414,25.3,22,154.00,66.25,34.0,95.8,87.9,99.2,59.6,...,24.67,20.302484,1.68275,69.853168,86.360,13.385834,34.606318,23.32,18.46,18.46
3,1.0751,10.4,26,184.75,72.25,37.4,101.8,86.4,101.2,60.1,...,24.88,20.559872,1.83515,83.801122,94.996,14.724417,34.015766,17.12,19.64,19.64
4,1.0340,28.7,24,184.25,71.25,34.4,97.3,100.0,101.9,63.2,...,25.52,21.320830,1.80975,83.574326,87.376,13.543314,39.370100,28.44,19.94,19.94

In [8]:
df.describe()

,Density,BodyFat,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,Knee,Ankle,Biceps,Forearm,Wrist,Height_Meters,Weight_kg,BMI,BMI Body Fat
count,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000,252.000000
mean,1.055574,19.150794,44.884921,178.924405,70.148810,37.992063,100.824206,92.555952,99.904762,59.405952,38.590476,23.102381,32.273413,28.663889,18.229762,1.781780,81.158679,25.942199,21.830639
std,0.019031,8.368740,12.602040,29.389160,3.662856,2.430913,8.430476,10.783077,7.164058,5.249952,2.411805,1.694893,3.021274,2.020691,0.933585,0.093037,13.330688,9.558451,11.470141
min,0.995000,0.000000,22.000000,118.500000,29.500000,31.100000,79.300000,69.400000,85.000000,47.200000,33.000000,19.100000,24.800000,21.000000,15.800000,0.749300,53.750652,18.017664,12.321197
25%,1.041400,12.475000,35.750000,159.000000,68.250000,36.400000,94.350000,84.575000,95.500000,56.000000,36.975000,22.000000,30.200000,27.300000,17.600000,1.733550,72.121128,23.035661,18.342793
50%,1.054900,19.200000,43.000000,176.500000,70.000000,38.000000,99.650000,90.950000,99.300000,59.000000,38.500000,22.800000,32.050000,28.700000,18.300000,1.778000,80.058988,25.094288,20.813145
75%,1.070400,25.300000,54.000000,197.000000,72.250000,39.425000,105.375000,99.325000,103.525000,62.350000,39.925000,24.000000,34.325000,30.000000,18.800000,1.835150,89.357624,27.334547,23.501457
max,1.108900,47.500000,81.000000,363.150000,77.750000,51.200000,136.200000,148.100000,147.700000,87.300000,49.100000,33.900000,45.000000,34.900000,21.400000,1.974850,164.721935,165.618094,189.441713

In [24]:
df['Height (m)'] = df['Height'] * 0.0254 # 1 inch = 0.0254 meters
df['Weight (kg)'] = df['Weight'] * 0.453592 # 1 pound = 0.453592 kilograms
df['BMI'] = df['Weight (kg)']/(df['Height (m)'] ** 2)
df['BMI'] = df['BMI'].round(2)
df.head(5)

,Density,BodyFat,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,...,BMI,BMI Body Fat,Height (m),Weight (kg),Height (cm),neck_in,abdomen_in,Navy_Body_Fat,BMI_Body_Fat_Percentage,BMI_Body_Fat
0,1.0708,12.3,23,154.25,67.75,36.2,93.1,85.2,94.5,59.0,...,23.63,19.052135,1.72085,69.966566,91.948,14.251976,33.543325,19.08,17.44,17.44
1,1.0853,6.1,22,173.25,72.25,38.5,93.6,83.0,98.7,58.7,...,23.33,18.701206,1.83515,78.584814,97.790,15.157489,32.677183,13.52,16.86,16.86
2,1.0414,25.3,22,154.00,66.25,34.0,95.8,87.9,99.2,59.6,...,24.67,20.302484,1.68275,69.853168,86.360,13.385834,34.606318,23.32,18.46,18.46
3,1.0751,10.4,26,184.75,72.25,37.4,101.8,86.4,101.2,60.1,...,24.88,20.559872,1.83515,83.801122,94.996,14.724417,34.015766,17.12,19.64,19.64
4,1.0340,28.7,24,184.25,71.25,34.4,97.3,100.0,101.9,63.2,...,25.52,21.320830,1.80975,83.574326,87.376,13.543314,39.370100,28.44,19.94,19.94

In [21]:
# Calculate the Body Fat Percentage using the given formula
df['BMI_Body_Fat'] = 1.20 * df['BMI'] + 0.23 * df['Age'] - 16.2

# Limit the output to two decimal points
df['BMI_Body_Fat'] = df['BMI_Body_Fat'].round(2)

# Save the updated DataFrame back to a CSV file
df.to_csv('bodyfat.csv', index=False)
df.head(10)

,Density,BodyFat,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,...,BMI,BMI Body Fat,Height (m),Weight (kg),Height (cm),neck_in,abdomen_in,Navy_Body_Fat,BMI_Body_Fat_Percentage,BMI_Body_Fat
0,1.0708,12.3,23,154.25,67.75,36.2,93.1,85.2,94.5,59.0,...,23.626779,19.052135,1.72085,69.966566,91.948,14.251976,33.543325,19.075319,17.44,17.44
1,1.0853,6.1,22,173.25,72.25,38.5,93.6,83.0,98.7,58.7,...,23.334338,18.701206,1.83515,78.584814,97.790,15.157489,32.677183,13.520855,16.86,16.86
2,1.0414,25.3,22,154.00,66.25,34.0,95.8,87.9,99.2,59.6,...,24.668737,20.302484,1.68275,69.853168,86.360,13.385834,34.606318,23.316541,18.46,18.46
3,1.0751,10.4,26,184.75,72.25,37.4,101.8,86.4,101.2,60.1,...,24.883227,20.559872,1.83515,83.801122,94.996,14.724417,34.015766,17.119175,19.64,19.64
4,1.0340,28.7,24,184.25,71.25,34.4,97.3,100.0,101.9,63.2,...,25.517358,21.320830,1.80975,83.574326,87.376,13.543314,39.370100,28.441266,19.94,19.94
5,1.0502,20.9,24,210.25,74.75,39.0,104.5,94.4,107.8,66.0,...,26.455231,22.446278,1.89865,95.367718,99.060,15.354339,37.165374,20.669945,21.07,21.07
6,1.0549,19.2,26,181.00,69.75,36.4,105.1,90.7,100.3,58.4,...,26.157010,22.088412,1.77165,82.100152,92.456,14.330716,35.708681,22.026725,21.17,21.17
7,1.0704,12.4,25,176.00,72.50,37.8,99.6,88.5,97.1,60.0,...,23.541526,18.949831,1.84150,79.832192,96.012,14.881898,34.842539,18.288072,17.80,17.80
8,1.0900,4.1,25,191.00,74.00,38.1,100.9,82.5,99.9,62.9,...,24.522677,20.127213,1.87960,86.636072,96.774,15.000008,32.480333,12.708823,18.98,18.98
9,1.0722,11.7,23,198.25,73.50,42.1,99.6,88.6,104.1,63.1,...,25.800996,21.661195,1.86690,89.924614,106.934,16.574812,34.881909,14.641269,20.05,20.05

###

In [22]:
# Convert height and abdomen from centimeters to inches (1 cm = 0.393701 inches)
df['neck_in'] = df['Neck'] * 0.393701
df['abdomen_in'] = df['Abdomen'] * 0.393701


# Calculate the Body Fat Percentage using the given formula
df['Navy_Body_Fat'] = (
    86.010 * np.log10(df['abdomen_in'] - df['neck_in']) -
    70.041 * np.log10(df['Height']) +
    36.76
)

# Limit the output to two decimal points
df['Navy_Body_Fat'] = df['Navy_Body_Fat'].round(2)

# Save the updated DataFrame back to a CSV file
df.to_csv('bodyfat.csv', index=False)
df.head(10)

,Density,BodyFat,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,...,BMI,BMI Body Fat,Height (m),Weight (kg),Height (cm),neck_in,abdomen_in,Navy_Body_Fat,BMI_Body_Fat_Percentage,BMI_Body_Fat
0,1.0708,12.3,23,154.25,67.75,36.2,93.1,85.2,94.5,59.0,...,23.626779,19.052135,1.72085,69.966566,91.948,14.251976,33.543325,19.08,17.44,17.44
1,1.0853,6.1,22,173.25,72.25,38.5,93.6,83.0,98.7,58.7,...,23.334338,18.701206,1.83515,78.584814,97.790,15.157489,32.677183,13.52,16.86,16.86
2,1.0414,25.3,22,154.00,66.25,34.0,95.8,87.9,99.2,59.6,...,24.668737,20.302484,1.68275,69.853168,86.360,13.385834,34.606318,23.32,18.46,18.46
3,1.0751,10.4,26,184.75,72.25,37.4,101.8,86.4,101.2,60.1,...,24.883227,20.559872,1.83515,83.801122,94.996,14.724417,34.015766,17.12,19.64,19.64
4,1.0340,28.7,24,184.25,71.25,34.4,97.3,100.0,101.9,63.2,...,25.517358,21.320830,1.80975,83.574326,87.376,13.543314,39.370100,28.44,19.94,19.94
5,1.0502,20.9,24,210.25,74.75,39.0,104.5,94.4,107.8,66.0,...,26.455231,22.446278,1.89865,95.367718,99.060,15.354339,37.165374,20.67,21.07,21.07
6,1.0549,19.2,26,181.00,69.75,36.4,105.1,90.7,100.3,58.4,...,26.157010,22.088412,1.77165,82.100152,92.456,14.330716,35.708681,22.03,21.17,21.17
7,1.0704,12.4,25,176.00,72.50,37.8,99.6,88.5,97.1,60.0,...,23.541526,18.949831,1.84150,79.832192,96.012,14.881898,34.842539,18.29,17.80,17.80
8,1.0900,4.1,25,191.00,74.00,38.1,100.9,82.5,99.9,62.9,...,24.522677,20.127213,1.87960,86.636072,96.774,15.000008,32.480333,12.71,18.98,18.98
9,1.0722,11.7,23,198.25,73.50,42.1,99.6,88.6,104.1,63.1,...,25.800996,21.661195,1.86690,89.924614,106.934,16.574812,34.881909,14.64,20.05,20.05

In [27]:
# List of columns to remove
columns_to_remove = ['BMI Body Fat', 'Height (m)', 'Weight (kg), 'neck_in', 'abdomen_in', 'Navy_Body_Fat', 'BMI_Body_Fat_Percentage', 'BMI_Body_Fat']

# Drop the specified columns
df = df.drop(columns=columns_to_remove)

# Save the updated DataFrame back to a CSV file
df.to_csv('bodyfat.csv', index=False)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3214651029.py, line 2)

In [ ]:
df.corr()

In [ ]:
from pandas.plotting import scatter_matrix
attributes = ['Weight', 'Neck', 'Thigh', 'Knee', 'Ankle',  'Biceps', 'Forearm', 'Wrist', 'BodyFat']
scatter_matrix(df[attributes])

In [ ]:
from pandas.plotting import scatter_matrix
attributes = ['Density', 'Height', 'Chest', 'Abdomen', 'Hip','BodyFat']
scatter_matrix(df[attributes])

In [ ]:
density = df['Density']
body_fat = df['BodyFat']

plt.scatter(body_fat, density)
plt.xlabel('Body Fat Percentage')
plt.ylabel('Density')
plt.show()

In [ ]:
age = df['Age']
body_fat = df['BodyFat']

plt.scatter(body_fat, age)
plt.xlabel('Body Fat Percentage')
plt.ylabel('Age')
plt.show()

In [ ]:
height = df['Height']
body_fat = df['BodyFat']

plt.scatter(body_fat, height)
plt.xlabel('Body Fat Percentage')
plt.ylabel('Height')
plt.show()

In [ ]:
neck = df['Neck']
body_fat = df['BodyFat']

plt.scatter(body_fat, neck)
plt.xlabel('Body Fat Percentage')
plt.ylabel('Neck')
plt.show()

In [ ]:
abdomen = df['Abdomen']
body_fat = df['BodyFat']

plt.scatter(body_fat, abdomen)
plt.xlabel('Body Fat Percentage')
plt.ylabel('Abdomen')
plt.show()

In [ ]:
abdomen = df['Hip']
body_fat = df['BodyFat']

plt.scatter(body_fat, hip)
plt.xlabel('Body Fat Percentage')
plt.ylabel('Hip')
plt.show()